import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";
import SearchUI from "@/components/searchUI";
import { UserSyncProvider } from "@/components/providers/user-sync-provider";

const notoSans = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "AI Notes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${notoSans.className} antialiased flex w-screen h-svh`}
      >
        <UserSyncProvider>
          <SearchUI />
          <Sidebar />
          {children}
        </UserSyncProvider>
      </body>
    </html>
  );
}
